### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by lihaitao123321** [songStar0904/yonghuishenghuo-wxapp#3]
你好，仿真度是100%？

**Comment by lihaitao123321** [comment]
那个addressComponent报错：Cannot read property 'addressComponent' of undefined;at pages/cart/cart onReady function;at api request success callback function
TypeError: Cannot read property 'addressComponent' of undefined

**Comment by songStar0904** [comment]
你好，因为我没有原设计稿，所以仿真度不是100%。
